on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
    - feature/*

name: My Workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: npm install, build, and test
      env:
        NODE_OPTIONS: --max-old-space-size=8192
      run: |
        npm install
        npm run build --if-present
        npm test